# Generated by Django 5.2.4 on 2025-07-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcode', models.CharField(max_length=10, unique=True)),
                ('original_url', models.URLField()),
                ('clicks', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
