# Generated by Django 5.2.2 on 2025-08-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_shorturl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GShortURL',
        ),
        migrations.DeleteModel(
            name='ShortURL',
        ),
    ]
